# Generated by Django 4.1.7 on 2023-03-14 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0002_appointment_date_alter_status_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='featured_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='BNstudio.service'),
        ),
    ]
