# Generated by Django 4.1.7 on 2023-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0003_servicecategory_featured_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
