# Generated by Django 4.1.7 on 2023-03-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Огляд', 'verbose_name_plural': 'Огляд'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id', 'title'], 'verbose_name': 'Послуги', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['id', 'title'], 'verbose_name': 'Категорії', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='title',
        ),
    ]
