# Generated by Django 4.1.7 on 2023-03-21 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0007_remove_customer_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='BNstudio.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='BNstudio.service')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BNstudio.cart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNstudio.service')),
            ],
            options={
                'unique_together': {('cart', 'service')},
            },
        ),
    ]
