# Generated by Django 4.1.7 on 2023-03-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0011_customer_birth_date_customer_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('cancel_order', 'Can cancel order')], 'verbose_name': 'Виконані замовлення', 'verbose_name_plural': 'Виконані замовлення'},
        ),
        migrations.AlterModelOptions(
            name='appointmentitem',
            options={'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RenameField(
            model_name='avability',
            old_name='end_time',
            new_name='slot_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='avability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BNstudio.paymentmethod'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BNstudio.staff'),
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BNstudio.service'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'No card'), ('S', '3 percent card'), ('G', '10 percent card')], default='B', max_length=1),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
