# Generated by Django 4.1.7 on 2023-03-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0014_alter_appointment_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentitem',
            old_name='end_time',
            new_name='time_slot',
        ),
        migrations.RenameField(
            model_name='avability',
            old_name='slot_time',
            new_name='time_slot',
        ),
        migrations.RemoveField(
            model_name='appointmentitem',
            name='start_time',
        ),
    ]
