# Generated by Django 4.1.7 on 2023-03-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0019_appointment_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avability',
            name='time_slot',
        ),
    ]
