# Generated by Django 4.1.7 on 2023-03-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0020_remove_avability_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmentitem',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='appointmentitem',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BNstudio.staff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
