# Generated by Django 4.1.7 on 2023-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0021_remove_appointmentitem_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='make_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
