# Generated by Django 4.2 on 2023-04-05 13:27

import BNstudio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0022_service_make_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=None, upload_to='BNstudio/images', validators=[BNstudio.validators.validate_file_size]),
        ),
    ]
