# Generated by Django 4.2 on 2023-04-05 13:28

import BNstudio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0023_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(upload_to='BNstudio/images', validators=[BNstudio.validators.validate_file_size]),
        ),
    ]
