# Generated by Django 4.2 on 2023-04-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0024_alter_customer_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avability',
            new_name='Availability',
        ),
    ]
