# Generated by Django 4.2 on 2023-04-21 13:48

import BNstudio.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0025_rename_avability_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(default=None, upload_to='BNstudio/images', validators=[BNstudio.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='availability',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='BNstudio.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('date', 'staff')},
        ),
    ]
