# Generated by Django 4.2 on 2023-04-21 13:48

import BNstudio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0026_servicecategory_image_alter_availability_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(upload_to='BNstudio/images', validators=[BNstudio.validators.validate_file_size]),
        ),
    ]
