# Generated by Django 4.2.1 on 2023-05-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0027_alter_servicecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.CreateModel(
            name='OnlineAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('time_slot', models.TimeField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('payment', models.CharField(blank=True, choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=50, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BNstudio.paymentmethod')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BNstudio.staff')),
            ],
            options={
                'verbose_name': 'Онлайн запис',
                'verbose_name_plural': 'Онлайн запис',
                'permissions': [('cancel_order', 'Can cancel order')],
            },
        ),
    ]
