# Generated by Django 4.2.1 on 2023-05-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0031_alter_onlineappointment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineappointment',
            options={'verbose_name': 'Онлайн запис', 'verbose_name_plural': 'Онлайн запис'},
        ),
        migrations.RenameField(
            model_name='onlineappointment',
            old_name='customer',
            new_name='name',
        ),
    ]
