# Generated by Django 4.2.1 on 2023-05-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNstudio', '0032_alter_onlineappointment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineappointment',
            old_name='date',
            new_name='appointmentDate',
        ),
        migrations.RenameField(
            model_name='onlineappointment',
            old_name='time_slot',
            new_name='appointmentTime',
        ),
        migrations.RenameField(
            model_name='onlineappointment',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='onlineappointment',
            old_name='service',
            new_name='serviceId',
        ),
        migrations.RenameField(
            model_name='onlineappointment',
            old_name='staff',
            new_name='staffId',
        ),
    ]
