# Generated by Django 4.1.2 on 2022-11-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'managed': False, 'verbose_name': 'Список майстрів', 'verbose_name_plural': 'Список майстрів'},
        ),
    ]
