# Generated by Django 4.1.2 on 2022-11-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_master_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='master',
            table='masters',
        ),
    ]
