# Generated by Django 4.1.2 on 2022-10-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False},
        ),
    ]
