# Generated by Django 4.1.2 on 2022-10-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
