# Generated by Django 4.1.2 on 2022-10-13 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_nails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masters',
            old_name='master_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='beauty_nails.services'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
