# Generated by Django 4.1.2 on 2022-10-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_nails', '0002_rename_master_name_masters_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Masters',
            new_name='Master',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
