# Generated by Django 4.1.2 on 2022-10-20 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.get_current_timezone)),
                ('client_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('master', models.CharField(max_length=50)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'managed': True,
            },
        ),
    ]
