# Generated by Django 4.1.2 on 2022-11-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': True, 'verbose_name': 'Запис клієнтів', 'verbose_name_plural': 'Запис клієнтів'},
        ),
    ]
