# Generated by Django 4.1.2 on 2023-01-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_master_table'),
        ('appointments', '0004_alter_appointment_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.master'),
        ),
    ]
