# Generated by Django 4.1.2 on 2022-10-19 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('clients', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.get_current_timezone)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master')),
                ('service', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
