# Generated by Django 4.1.2 on 2022-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderwithclientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('service_name', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Онлайн запис',
                'verbose_name_plural': 'Онлайн запис',
                'db_table': 'orders_clients',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'Список замовлень', 'verbose_name_plural': 'Список замовлень'},
        ),
    ]
