# Generated by Django 4.1.2 on 2023-01-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicecategory'),
        ('masters', '0003_alter_master_table'),
        ('orders', '0006_alter_order_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_client',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.master'),
        ),
        migrations.AlterField(
            model_name='order_client',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service'),
        ),
    ]
